# Generated by Django 5.2.4 on 2025-08-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('percentage', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('branch', models.CharField(max_length=100, verbose_name='Филиал')),
                ('cost_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='% себестоимости')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Сумма')),
                ('client_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Процент клиента')),
                ('supplier_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Процент поставщика')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Оплаченная сумма')),
                ('documents', models.BooleanField(default=False, verbose_name='Документы')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клиент')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'default_permissions': (),
            },
        ),
    ]
