# Generated by Django 5.2.5 on 2025-08-28 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип счета')),
            ],
            options={
                'verbose_name': 'Тип счета',
                'verbose_name_plural': 'Типы счетов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Данные для баланса',
                'verbose_name_plural': 'Данные для баланса',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('percentage', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Процент')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Инвестор')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Изначальный баланс')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('operation_type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], default='expense', max_length=10, verbose_name='Тип операции')),
            ],
            options={
                'verbose_name': 'Назначение платежа',
                'verbose_name_plural': 'Назначения платежей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Баланс поставщика')),
            ],
            options={
                'verbose_name': 'Счет поставщика',
                'verbose_name_plural': 'Счета поставщиков',
            },
        ),
        migrations.CreateModel(
            name='SupplierDebtRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма погашения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Погашение долга поставщика',
                'verbose_name_plural': 'Погашения долгов поставщиков',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Сумма')),
                ('client_percentage', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='%')),
                ('bonus_percentage', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='%')),
                ('supplier_percentage', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='%')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Оплачено')),
                ('documents', models.BooleanField(default=False, verbose_name='Документы')),
                ('returned_by_supplier', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Возвращено')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('returned_bonus', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Возвращено бонуса')),
                ('returned_to_client', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Возвращено клиенту')),
                ('returned_to_investor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Возвращено инвестору')),
                ('modified_by_accountant', models.BooleanField(default=False, verbose_name='Изменено бухгалтером')),
                ('viewed_by_admin', models.BooleanField(default=False, verbose_name='Просмотрено администратором')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Баланс')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='main.accounttype', verbose_name='Тип счета')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-balance', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvestorDebtOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('deposit', 'Внесение'), ('withdrawal', 'Забор')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_operations', to='main.investor', verbose_name='Инвестор')),
            ],
            options={
                'verbose_name': 'Операция с долгом инвестора',
                'verbose_name_plural': 'Операции с долгами инвесторов',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Сумма перевода')),
                ('transfer_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата перевода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='main.account', verbose_name='Счет получателя')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='main.account', verbose_name='Счет отправителя')),
            ],
            options={
                'verbose_name': 'Перевод средств',
                'verbose_name_plural': 'Переводы средств',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('returned_to_investor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Возвращено инвестору')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='main.account', verbose_name='Счет')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_flows', to='main.paymentpurpose', verbose_name='Назначение платежа')),
            ],
            options={
                'verbose_name': 'Движение ДС',
                'verbose_name_plural': 'Движение ДС',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('cost_percentage', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='%')),
                ('visible_for_assistant', models.BooleanField(default=True, verbose_name='Видим для ассистента')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='main.branch', verbose_name='Филиал')),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_suppliers', to='main.account', verbose_name='Расчетный счет')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
