# Generated by Django 5.2.5 on 2025-09-07 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='destination_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='main.supplier', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='source_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='main.supplier', verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='main.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='supplieraccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_accounts', to='main.account', verbose_name='Счет'),
        ),
        migrations.AddField(
            model_name='supplieraccount',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_accounts', to='main.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='account',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='accounts', through='main.SupplierAccount', to='main.supplier', verbose_name='Поставщики'),
        ),
        migrations.AddField(
            model_name='supplierdebtrepayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_repayments', to='main.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.account', verbose_name='Счет'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='main.transaction', verbose_name='Связанная транзакция'),
        ),
        migrations.AlterUniqueTogether(
            name='supplieraccount',
            unique_together={('supplier', 'account')},
        ),
    ]
