# Generated by Django 5.2.5 on 2025-09-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='%'),
        ),
    ]
