# Generated by Django 5.2.5 on 2025-09-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('from_us', 'От нас'), ('to_us', 'Нам')], max_length=10, null=True, verbose_name='Тип перевода'),
        ),
    ]
