# Generated by Django 5.2.5 on 2025-08-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorDebtOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('deposit', 'Внесение'), ('withdrawal', 'Забор')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_operations', to='main.investor', verbose_name='Инвестор')),
            ],
            options={
                'verbose_name': 'Операция с долгом инвестора',
                'verbose_name_plural': 'Операции с долгами инвесторов',
                'ordering': ['created_at'],
            },
        ),
    ]
