# Generated by Django 5.2.4 on 2025-08-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaction_bonus_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='%'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='%'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='supplier_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='%'),
        ),
    ]
