# Generated by Django 5.2.5 on 2025-09-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_moneytransfer_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='is_counted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Учитывать в итогах'),
        ),
    ]
