# Generated by Django 5.2.4 on 2025-08-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_transaction_bonus_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='modified_by_accountant',
            field=models.BooleanField(default=False, verbose_name='Изменено бухгалтером'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='viewed_by_admin',
            field=models.BooleanField(default=False, verbose_name='Просмотрено администратором'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Оплачено'),
        ),
    ]
