# Generated by Django 5.2.4 on 2025-08-04 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_transaction_modified_by_accountant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип счета')),
            ],
            options={
                'verbose_name': 'Тип счета',
                'verbose_name_plural': 'Типы счетов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название счета')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Баланс')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='main.accounttype', verbose_name='Тип счета')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-balance', 'name'],
            },
        ),
    ]
