# Generated by Django 5.2.5 on 2025-08-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Данные для баланса',
                'verbose_name_plural': 'Данные для баланса',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
