# Generated by Django 5.2.5 on 2025-09-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_moneytransfer_is_counted'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
