# Generated by Django 5.2.5 on 2025-09-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cashflow_created_by_investordebtoperation_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='initial_balance',
        ),
    ]
