# Generated by Django 5.2.5 on 2025-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_investor_initial_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investordebtoperation',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Внесение'), ('withdrawal', 'Забор'), ('profit', 'Прибыль')], max_length=10, verbose_name='Тип операции'),
        ),
    ]
