# Generated by Django 5.2.4 on 2025-08-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_accounttype_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Сумма')),
                ('purpose', models.CharField(max_length=255, verbose_name='Назначение платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='main.account', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Движение ДС',
                'verbose_name_plural': 'Движение ДС',
                'ordering': ['-created_at'],
            },
        ),
    ]
