# Generated by Django 5.2.5 on 2025-09-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_moneytransfer_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='visible_in_summary',
            field=models.BooleanField(default=True, verbose_name='Виден в остатках'),
        ),
    ]
