# Generated by Django 5.2.5 on 2025-08-25 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_balancedata_delete_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
