# Generated by Django 5.2.5 on 2025-09-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_supplier_visible_in_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierdebtrepayment',
            name='transaction',
        ),
    ]
