# Generated by Django 5.2.5 on 2025-08-25 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_balancedata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
