# Generated by Django 5.2.4 on 2025-08-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cashflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='percentage',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Процент'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cost_percentage',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='% себестоимости'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='%'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client_percentage',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='%'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='supplier_percentage',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='%'),
        ),
    ]
