# Generated by Django 5.2.5 on 2025-09-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_investordebtoperation_operation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'ТМЦ',
                'verbose_name_plural': 'ТМЦ',
                'ordering': ['name'],
            },
        ),
    ]
