# Generated by Django 5.2.4 on 2025-08-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_client_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cost_percentage',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='%'),
        ),
        migrations.CreateModel(
            name='SupplierAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_accounts', to='main.account', verbose_name='Счет')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_accounts', to='main.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Привязка счета',
                'verbose_name_plural': 'Привязки счетов',
                'unique_together': {('supplier', 'account')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='accounts', through='main.SupplierAccount', to='main.supplier', verbose_name='Поставщики'),
        ),
    ]
