# Generated by Django 5.2.5 on 2025-08-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_investor_created_at_alter_transaction_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
