# Generated by Django 5.2.4 on 2025-08-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_supplier_cost_percentage_supplieraccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieraccount',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Баланс поставщика'),
        ),
    ]
