# Generated by Django 5.2.5 on 2025-08-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_monthlycapital'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='visible_for_assistant',
            field=models.BooleanField(default=True, verbose_name='Видим для ассистента'),
        ),
    ]
