# Generated by Django 5.2.4 on 2025-08-05 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_supplieraccount_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Назначение платежа',
                'verbose_name_plural': 'Назначения платежей',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_flows', to='main.paymentpurpose', verbose_name='Назначение платежа'),
        ),
    ]
