# Generated by Django 5.2.4 on 2025-08-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_paymentpurpose_alter_cashflow_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['id'], 'verbose_name': 'Движение ДС', 'verbose_name_plural': 'Движение ДС'},
        ),
        migrations.AddField(
            model_name='paymentpurpose',
            name='operation_type',
            field=models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], default='expense', max_length=10, verbose_name='Тип операции'),
        ),
    ]
