# Generated by Django 5.2.5 on 2025-11-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_clientdebtrepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
