# Generated by Django 5.2.5 on 2025-12-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_moneytransfer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fully_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата полной оплаты и погашения долгов'),
        ),
    ]
