# Generated by Django 5.2.5 on 2025-08-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_supplierdebtrepayment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='returned_to_investor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Возвращено инвестору'),
        ),
    ]
