# Generated by Django 5.2.5 on 2025-08-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_transaction_returned_to_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Изначальный баланс'),
        ),
    ]
