# Generated by Django 5.2.5 on 2026-01-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_transaction_fully_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdebtrepayment',
            name='cash_flow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_debt_repayment', to='main.cashflow', verbose_name='Связанное движение ДС'),
        ),
        migrations.AddField(
            model_name='clientdebtrepayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_debt_repayments', to='main.transaction', verbose_name='Связанная транзакция'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fully_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
    ]
