# Generated by Django 5.2.4 on 2025-08-06 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_suppliers', to='main.account', verbose_name='Счет'),
        ),
    ]
