# Generated by Django 5.2.4 on 2025-08-06 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_supplier_default_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='main.supplier', verbose_name='Поставщик'),
        ),
    ]
