# Generated by Django 5.2.5 on 2026-01-27 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_clientdebtrepayment_cash_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdebtrepayment',
            name='cash_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_debt_repayments', to='main.cashflow', verbose_name='Связанное движение ДС'),
        ),
    ]
