# Generated by Django 5.2.5 on 2025-08-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
