# Generated by Django 5.2.4 on 2025-08-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cashflow_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='main.transaction', verbose_name='Связанная транзакция'),
        ),
    ]
