# Generated by Django 5.2.5 on 2025-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cashflow_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='returned_to_investor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Возвращено инвестору'),
        ),
    ]
