# Generated by Django 5.2.4 on 2025-08-07 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cashflow_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='default_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_suppliers', to='main.account', verbose_name='Расчетный счет'),
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Сумма перевода')),
                ('transfer_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата перевода')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='main.account', verbose_name='Счет получателя')),
                ('destination_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='main.supplier', verbose_name='Получатель')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='main.account', verbose_name='Счет отправителя')),
                ('source_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='main.supplier', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Перевод средств',
                'verbose_name_plural': 'Переводы средств',
                'ordering': ['id'],
            },
        ),
    ]
