# Generated by Django 5.2.5 on 2025-08-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_supplier_default_account_moneytransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='returned_by_supplier',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Возвращено'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
    ]
