# Generated by Django 5.2.5 on 2025-08-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_transaction_returned_by_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='branch',
        ),
    ]
