# Generated by Django 5.2.5 on 2025-08-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_branch_supplier_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDebtRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма погашения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_repayments', to='main.supplier', verbose_name='Поставщик')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_repayments', to='main.transaction', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Погашение долга поставщика',
                'verbose_name_plural': 'Погашения долгов поставщиков',
                'ordering': ['-created_at'],
            },
        ),
    ]
