# Generated by Django 5.2.5 on 2025-08-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_supplierdebtrepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplieraccount',
            options={'verbose_name': 'Счет поставщика', 'verbose_name_plural': 'Счета поставщиков'},
        ),
        migrations.AlterModelOptions(
            name='supplierdebtrepayment',
            options={'ordering': ['created_at'], 'verbose_name': 'Погашение долга поставщика', 'verbose_name_plural': 'Погашения долгов поставщиков'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='returned_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Возвращено бонуса'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='returned_to_client',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Возвращено клиенту'),
        ),
    ]
