# Generated by Django 5.2.5 on 2025-08-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_webauthncredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthncredential',
            name='credential_id',
            field=models.BinaryField(),
        ),
    ]
