# Generated by Django 5.2.5 on 2025-08-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_webauthncredential_credential_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webauthncredential',
            options={'verbose_name': 'WebAuthn Credential', 'verbose_name_plural': 'WebAuthn Credentials'},
        ),
    ]
