# Generated by Django 5.2.5 on 2025-08-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_transaction_returned_by_supplier_and_more'),
        ('users', '0006_alter_webauthncredential_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.supplier', verbose_name='Поставщик'),
        ),
    ]
