# Generated by Django 5.2.5 on 2025-08-13 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_supplier_user'),
        ('users', '0007_user_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='main.supplier'),
        ),
    ]
