# Generated by Django 5.2.5 on 2025-08-13 11:11

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_managers_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, default=users.models.get_default_user_type, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usertype', verbose_name='Тип пользователя'),
        ),
    ]
